### ISSUE TITLE
Possible early free bug

### ISSUE THREAD

**Issue by apnadkarni** [BessyHDFViewer/HDFpp#1]
If the following method is called with self assignment (`o = o;`)

```
	SWObject& operator = (const SWObject& obj) {
		if (ptr) Tcl_DecrRefCount(ptr);
		ptr = obj.ptr;
		if (ptr) Tcl_IncrRefCount(ptr);
		return *this;
	}
```
I think the Tcl_Obj will (potentially) be freed and then the increment occurs on a freed Tcl_Obj. Either there should be a guard that checks `ptr==obj.ptr` or `obj.ptr` should be incremented before decrementing `ptr`.

Very nice app BTW.

**Comment by auriocus** [comment]
Thank you for revieweing the code! I had not considered self-assignment. 
Should be fixed now with #c5d384b
